### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by adhe222** [t3rn/executor-release#8]
{"level":"error","time":1734958721678,"code":"NETWOR
K_ERROR","error":"could not detect network (event=\"
noNetwork\", code=NETWORK_ERROR, version=providers/5
.7.2)","msg":"🚨 Failed to get balance of the execut
or on destination network."}
{"level":"error","time":1734958721679,"code":"NETWOR
K_ERROR","error":"could not detect network (event=\"
noNetwork\", code=NETWORK_ERROR, version=providers/5
.7.2)","msg":"🚨 Failed to get balance of the execut
or on destination network."}
server-out.js:3109
          var error = new Error(message);
                      ^
Error: could not detect network (event="noNetwork",
code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger8.makeError (server-out.js:3109:23)
    at Logger8.throwError (server-out.js:3118:22)
    at JsonRpcProvider2.<anonymous> (server-out.js:2
8790:38)
    at step (server-out.js:28209:21)
    at Object.throw (server-out.js:28161:18)
    at rejected (server-out.js:28140:36) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}

**Comment by dongsanxiang** [comment]
I also encountered this problem, how to solve it
![image](https://github.com/user-attachments/assets/09e6964f-229c-4eb0-9b41-936dfd509739)

**Comment by weikaide-web3** [comment]
suppose you need to use your RPC instead of the public one.

**Comment by Bvvvp009** [comment]
use Alchemy free RPC endpoints.

**Comment by dongsanxiang** [comment]
how to set the free RPC endspoints,sir? can u show me the code?
just like export XXX_NETWORK = xxxx ?

**Comment by 3h4x** [comment]
@dongsanxiang @weikaide-web3 @weikaide-web3 problem should be fixed now!
